/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizModal {
        "size": any;
        "titleModal": any;
        "triggerElementId": string;
    }
}
declare global {
    interface HTMLWizModalElement extends Components.WizModal, HTMLStencilElement {
    }
    var HTMLWizModalElement: {
        prototype: HTMLWizModalElement;
        new (): HTMLWizModalElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-modal": HTMLWizModalElement;
    }
}
declare namespace LocalJSX {
    interface WizModal {
        "size"?: any;
        "titleModal"?: any;
        "triggerElementId"?: string;
    }
    interface IntrinsicElements {
        "wiz-modal": WizModal;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-modal": LocalJSX.WizModal & JSXBase.HTMLAttributes<HTMLWizModalElement>;
        }
    }
}
