/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { TimelineDataInterface, } from "./models/timeline-data.interface";
export namespace Components {
    interface WizTimeline {
        "completedDotColor": string;
        "currentDotColor": string;
        "dotColor": string;
        "progressBarColor": string;
        "progressColor": string;
        "textColor": string;
        "timelineData": Array<TimelineDataInterface>;
    }
}
declare global {
    interface HTMLWizTimelineElement extends Components.WizTimeline, HTMLStencilElement {
    }
    var HTMLWizTimelineElement: {
        prototype: HTMLWizTimelineElement;
        new (): HTMLWizTimelineElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-timeline": HTMLWizTimelineElement;
    }
}
declare namespace LocalJSX {
    interface WizTimeline {
        "completedDotColor"?: string;
        "currentDotColor"?: string;
        "dotColor"?: string;
        "progressBarColor"?: string;
        "progressColor"?: string;
        "textColor"?: string;
        "timelineData"?: Array<TimelineDataInterface>;
    }
    interface IntrinsicElements {
        "wiz-timeline": WizTimeline;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-timeline": LocalJSX.WizTimeline & JSXBase.HTMLAttributes<HTMLWizTimelineElement>;
        }
    }
}
