# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
  - master
  - release/*

pr:
  - master
  - release/*

variables:
  SiteDirectory: '$(Build.SourcesDirectory)/wizis-web'
  MonoRepoDirectory: '$(Build.SourcesDirectory)/syz'
  NgSyzDirectory: '$(Build.SourcesDirectory)/packages/ng-syz'

resources:
  repositories:
    - repository: site
      type: git
      name: DesignSystem/wizis-web
      ref: refs/heads/master
    - repository: this
      type: github
      endpoint: wizsolucoesAdminPAT
      name: wizsolucoes/syz
      ref: '$(Build.SourceBranch)'

pool:
  vmImage: 'ubuntu-latest'

stages:
  - stage: Build
    jobs:
      - job: Build
        displayName: 'Test and Build'
        condition: not(or(startsWith(variables['Build.SourceBranch'], 'refs/heads/release/'), eq(variables['build.sourceBranch'], 'refs/heads/master')))
        steps:
          # Build  and test components
          - checkout: this
          - checkout: site
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: ci
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Bootstrap'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run bootstrap'
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Test'
            inputs:
              command: 'custom'
              verbose: false
              customCommand: 'run test'
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'
              workingDir: $(MonoRepoDirectory)
  - stage: Stage
    displayName: 'Stage Solution'
    condition: startsWith(variables['Build.SourceBranch'], 'refs/heads/xpto/')
    jobs:
      - job: NgSyz
        pool:
          vmImage: 'windows-latest'
        displayName: 'Publish NgSyz to staging'
        steps:
          - checkout: this

          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: 'install'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Build lib'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run build:lib:prod'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Test lib'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run test:lib'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Build app'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run build:app:prod'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Test app'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run test:app'
              workingDir: $(NgSyzDirectory)

          - task: AzureFileCopy@4
            displayName: 'Publish app to storage'
            inputs:
              SourcePath: '$(NgSyzDirectory)/dist/app/*'
              azureSubscription: 'AmbientesDevHml'
              Destination: 'AzureBlob'
              storage: 'sysstorybookhmlstg'
              ContainerName: '$web'

      - job: Site
        displayName: 'Publish Syz site to staging'
        condition: 'false'
        steps:
          - checkout: this
          - checkout: site

          # Build components
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: ci
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Bootstrap'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run bootstrap'
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'
              workingDir: $(MonoRepoDirectory)

          # Build site documentaion and publish site
          - task: Npm@1
            displayName: 'Install site dependencies'
            inputs:
              command: ci
              workingDir: $(SiteDirectory)
          - script: node docs.js --site-path=$(SiteDirectory)
            displayName: 'Generate site documentation'
            workingDirectory: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Build site'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'
              workingDir: $(SiteDirectory)
          - task: CopyFiles@2
            displayName: 'Copy site dist to artifact staging directory'
            inputs:
              SourceFolder: '$(SiteDirectory)/dist/angular-wiz-repositorio'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: ArchiveFiles@2
            displayName: 'Archive site dist'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
              includeRootFolder: false
          - task: AzureWebApp@1
            displayName: 'Deploy site to Azure Web App'
            inputs:
              azureSubscription: '$(HML_SITE_AZURE_SUBSCRIPTION)'
              appType: webApp
              appName: '$(HML_SITE_APP_NAME)'
              package: $(System.ArtifactsDirectory)/*.zip
  - stage: Publish
    condition: eq(variables['build.sourceBranch'], 'refs/heads/release/ng-syz')
    jobs:
      - job: Publish
        displayName: 'Bump versions and publish'
        condition: succeeded()
        steps:
          - checkout: this
            persistCredentials: 'true'
          - checkout: site

          # Configure Lerna Bot
          - task: CmdLine@2
            displayName: Configure Lerna Bot
            inputs:
              script: |
                git config --global user.email "lernabot@wizsolucoes.com.br"
                git config --global user.name "Lerna bot"
              workingDirectory: $(MonoRepoDirectory)
          - task: CmdLine@2
            displayName: Checkout release/ng-syz
            inputs:
              script: 'git checkout release/ng-syz'
              workingDirectory: $(MonoRepoDirectory)

          # Build and test components
          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: ci
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Bootstrap'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run bootstrap'
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'
              workingDir: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Test'
            inputs:
              command: 'custom'
              verbose: false
              customCommand: 'run test'
              workingDir: $(MonoRepoDirectory)

          # Version and publish components
          - task: Npm@1
            displayName: 'Bump versions'
            inputs:
              command: 'custom'
              verbose: true
              customCommand: 'run version'
              workingDir: $(MonoRepoDirectory)

          # Build before publishing to get updated packages.json version
          - task: Npm@1
            displayName: 'Build'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'
              workingDir: $(MonoRepoDirectory)

          - task: Npm@1
            displayName: 'Publish'
            inputs:
              command: 'custom'
              customCommand: 'run release'
              customEndpoint: 'npmjs'
              workingDir: $(MonoRepoDirectory)

          # Build site documentaion and publish site
          - task: Npm@1
            displayName: 'Install site dependencies'
            inputs:
              command: ci
              workingDir: $(SiteDirectory)
          - script: node docs.js --site-path=$(SiteDirectory)
            displayName: 'Generate site documentation'
            workingDirectory: $(MonoRepoDirectory)
          - task: Npm@1
            displayName: 'Build site'
            inputs:
              command: custom
              verbose: false
              customCommand: 'run build'
              workingDir: $(SiteDirectory)
          - task: CopyFiles@2
            displayName: 'Copy site dist to artifact staging directory'
            inputs:
              SourceFolder: '$(SiteDirectory)/dist/angular-wiz-repositorio'
              Contents: '**'
              TargetFolder: '$(Build.ArtifactStagingDirectory)'
          - task: ArchiveFiles@2
            displayName: 'Archive site dist'
            inputs:
              rootFolderOrFile: '$(Build.ArtifactStagingDirectory)'
              includeRootFolder: false
          - task: AzureWebApp@1
            displayName: 'Deploy site to Azure Web App'
            inputs:
              azureSubscription: '$(PRD_SITE_AZURE_SUBSCRIPTION)'
              appType: webApp
              appName: '$(PRD_SITE_APP_NAME)'
              package: $(System.ArtifactsDirectory)/*.zip

      - job: NgSyz
        pool:
          vmImage: 'windows-latest'
        displayName: 'Publish NgSyz to production'
        steps:
          - checkout: this

          - task: Npm@1
            displayName: 'Install dependencies'
            inputs:
              command: 'install'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Build lib'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run build:lib:prod'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Test lib'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run test:lib'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Build app'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run build:app:prod'
              workingDir: $(NgSyzDirectory)

          - task: Npm@1
            displayName: 'Test app'
            inputs:
              command: custom
              verbose: true
              customCommand: 'run test:app'
              workingDir: $(NgSyzDirectory)

          - task: AzureFileCopy@4
            displayName: 'Publish app to storage'
            inputs:
              SourcePath: '$(NgSyzDirectory)/dist/app/*'
              azureSubscription: 'AmbienteCorporativoExterior'
              Destination: 'AzureBlob'
              storage: 'sysstorybookprdstg'
              ContainerName: '$web'
