/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizTab {
        "active": boolean;
        "type": string;
        "value": any;
    }
    interface WizTabs {
        "vertical": boolean;
    }
}
declare global {
    interface HTMLWizTabElement extends Components.WizTab, HTMLStencilElement {
    }
    var HTMLWizTabElement: {
        prototype: HTMLWizTabElement;
        new (): HTMLWizTabElement;
    };
    interface HTMLWizTabsElement extends Components.WizTabs, HTMLStencilElement {
    }
    var HTMLWizTabsElement: {
        prototype: HTMLWizTabsElement;
        new (): HTMLWizTabsElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-tab": HTMLWizTabElement;
        "wiz-tabs": HTMLWizTabsElement;
    }
}
declare namespace LocalJSX {
    interface WizTab {
        "active"?: boolean;
        "onReturnEvent"?: (event: CustomEvent<any>) => void;
        "type"?: string;
        "value"?: any;
    }
    interface WizTabs {
        "onTabChosen"?: (event: CustomEvent<any>) => void;
        "vertical"?: boolean;
    }
    interface IntrinsicElements {
        "wiz-tab": WizTab;
        "wiz-tabs": WizTabs;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-tab": LocalJSX.WizTab & JSXBase.HTMLAttributes<HTMLWizTabElement>;
            "wiz-tabs": LocalJSX.WizTabs & JSXBase.HTMLAttributes<HTMLWizTabsElement>;
        }
    }
}
