/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizTooltip {
        "activeBorder": boolean;
        "bgColor": any;
        "direction": any;
        "labelColor": any;
        "open": boolean;
        "size": any;
    }
}
declare global {
    interface HTMLWizTooltipElement extends Components.WizTooltip, HTMLStencilElement {
    }
    var HTMLWizTooltipElement: {
        prototype: HTMLWizTooltipElement;
        new (): HTMLWizTooltipElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-tooltip": HTMLWizTooltipElement;
    }
}
declare namespace LocalJSX {
    interface WizTooltip {
        "activeBorder"?: boolean;
        "bgColor"?: any;
        "direction"?: any;
        "labelColor"?: any;
        "open"?: boolean;
        "size"?: any;
    }
    interface IntrinsicElements {
        "wiz-tooltip": WizTooltip;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-tooltip": LocalJSX.WizTooltip & JSXBase.HTMLAttributes<HTMLWizTooltipElement>;
        }
    }
}
