/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizToggle {
        "disabled": boolean;
        "status": any;
    }
}
declare global {
    interface HTMLWizToggleElement extends Components.WizToggle, HTMLStencilElement {
    }
    var HTMLWizToggleElement: {
        prototype: HTMLWizToggleElement;
        new (): HTMLWizToggleElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-toggle": HTMLWizToggleElement;
    }
}
declare namespace LocalJSX {
    interface WizToggle {
        "disabled"?: boolean;
        "onReturnEvent"?: (event: CustomEvent<any>) => void;
        "status"?: any;
    }
    interface IntrinsicElements {
        "wiz-toggle": WizToggle;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-toggle": LocalJSX.WizToggle & JSXBase.HTMLAttributes<HTMLWizToggleElement>;
        }
    }
}
