/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizRadio {
        "disabled": boolean;
        "name": any;
        "value": any;
    }
    interface WizRadioGroup {
    }
}
declare global {
    interface HTMLWizRadioElement extends Components.WizRadio, HTMLStencilElement {
    }
    var HTMLWizRadioElement: {
        prototype: HTMLWizRadioElement;
        new (): HTMLWizRadioElement;
    };
    interface HTMLWizRadioGroupElement extends Components.WizRadioGroup, HTMLStencilElement {
    }
    var HTMLWizRadioGroupElement: {
        prototype: HTMLWizRadioGroupElement;
        new (): HTMLWizRadioGroupElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-radio": HTMLWizRadioElement;
        "wiz-radio-group": HTMLWizRadioGroupElement;
    }
}
declare namespace LocalJSX {
    interface WizRadio {
        "disabled"?: boolean;
        "name"?: any;
        "onReturnEvent"?: (event: CustomEvent<any>) => void;
        "value"?: any;
    }
    interface WizRadioGroup {
        "onValueChosen"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "wiz-radio": WizRadio;
        "wiz-radio-group": WizRadioGroup;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-radio": LocalJSX.WizRadio & JSXBase.HTMLAttributes<HTMLWizRadioElement>;
            "wiz-radio-group": LocalJSX.WizRadioGroup & JSXBase.HTMLAttributes<HTMLWizRadioGroupElement>;
        }
    }
}
