/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizAutocomplete {
        "data": any;
        "placeholder": any;
        "searchActive": any;
        "searchItem": any;
        "searchResult": any;
    }
}
declare global {
    interface HTMLWizAutocompleteElement extends Components.WizAutocomplete, HTMLStencilElement {
    }
    var HTMLWizAutocompleteElement: {
        prototype: HTMLWizAutocompleteElement;
        new (): HTMLWizAutocompleteElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-autocomplete": HTMLWizAutocompleteElement;
    }
}
declare namespace LocalJSX {
    interface WizAutocomplete {
        "data"?: any;
        "onReturnAutoComplete"?: (event: CustomEvent<any>) => void;
        "placeholder"?: any;
        "searchActive"?: any;
        "searchItem"?: any;
        "searchResult"?: any;
    }
    interface IntrinsicElements {
        "wiz-autocomplete": WizAutocomplete;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-autocomplete": LocalJSX.WizAutocomplete & JSXBase.HTMLAttributes<HTMLWizAutocompleteElement>;
        }
    }
}
