/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizCopy {
        "copiedAction": boolean;
        "labelCopied": string;
        "square": string;
        "squareColor": string;
        "time": string;
        "value": string;
    }
}
declare global {
    interface HTMLWizCopyElement extends Components.WizCopy, HTMLStencilElement {
    }
    var HTMLWizCopyElement: {
        prototype: HTMLWizCopyElement;
        new (): HTMLWizCopyElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-copy": HTMLWizCopyElement;
    }
}
declare namespace LocalJSX {
    interface WizCopy {
        "copiedAction"?: boolean;
        "labelCopied"?: string;
        "square"?: string;
        "squareColor"?: string;
        "time"?: string;
        "value"?: string;
    }
    interface IntrinsicElements {
        "wiz-copy": WizCopy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-copy": LocalJSX.WizCopy & JSXBase.HTMLAttributes<HTMLWizCopyElement>;
        }
    }
}
