/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface WizPrivacy {
    }
}
declare global {
    interface HTMLWizPrivacyElement extends Components.WizPrivacy, HTMLStencilElement {
    }
    var HTMLWizPrivacyElement: {
        prototype: HTMLWizPrivacyElement;
        new (): HTMLWizPrivacyElement;
    };
    interface HTMLElementTagNameMap {
        "wiz-privacy": HTMLWizPrivacyElement;
    }
}
declare namespace LocalJSX {
    interface WizPrivacy {
    }
    interface IntrinsicElements {
        "wiz-privacy": WizPrivacy;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "wiz-privacy": LocalJSX.WizPrivacy & JSXBase.HTMLAttributes<HTMLWizPrivacyElement>;
        }
    }
}
